@startuml
title Development cycle

'left to right direction
skinparam style strictuml

actor U  as "User"
component C  as "Code"
actor D  as "Developer"
component B  as "Bug Report"
actor T  as "Tester"
component R  as "Requirements"
component PR  as "Prioritised Requirements"
component TC as "Test Case"
'actor P  as "Publisher"
component RN as "Release Note"
actor M as "Owner"

D -r-> C : writes
B  .u.> D  : prompts
T -r-> TC : drafts
U  --> R  : describes
R  --> PR
M --> PR : selects
TC <.. PR  : is traced to

TC  -u-> C : evaluates
TC  -u-> B  : [fail] produces

M <-- C  : is published by
M --> RN : publishes (with code)
RN ..> U : informs

@enduml


=================================================================


@startuml
title Where development artifacts actually live

skinparam style strictuml
left to right direction

' ===== Artifacts =====
artifact Code
artifact "Bug Report" as Bug
artifact Requirements
artifact "Prioritised Requirements" as PR
together{
artifact "Test Cases (expected results)" as TCH
artifact "Test Cases (inputs)" as TCM
artifact "Test Runner" as TR
}
artifact "Release Notes" as RN

' ===== Storage / Systems =====
node JIRA
node Confluence
node "Windows Network" as Win
node Email

' ===== Mappings =====
Bug --> JIRA

Requirements --> Confluence
PR --> JIRA

Code --> Confluence
Code --> Win

TCH --> Confluence
TCM --> Win

TR --> Win

RN --> Confluence
RN --> Email

@enduml

